### ISSUE TITLE
GitBook documentation

### ISSUE THREAD

**Issue by gabrielspadon** [AISViz/aisdb-client#10]
@AISViz/maintainers, we need to migrate the documentation and the Python API references that are current on the ReadTheDocs platform to the GitBook platform. I hope this will make the documentation part more straightforward and help us to produce more content that can show users how to use the tools we developed and will be developing in the future. The GitBook account and directory for AISdb documentation have already been created, but all the links and references are broken. We probably need to fix them by hand. This tends to be a lot of work initially but probably will save us time later on.

**Comment by JayKumarr** [comment]
The examples mentioned in the Gitlab documentation are not working in the current version of code. Thus, each example has to be tested. 

I tested loading the **test_data_20210701.csv** into Sqlite database, it is processing but also mentions an error.
I tested the visualization piece of code which starts a server to visualize, but it is also not working

**Comment by gabrielspadon** [comment]
Do we know where that issue is coming from? Maybe from the AISdb backend?

**Comment by JayKumarr** [comment]
> Do we know where that issue is coming from? Maybe from the AISdb backend?

I have not started investigating yet. I will start soon.
