### ISSUE TITLE
Executing a piece of code to load csv into Postgres server

### ISSUE THREAD

**Issue by JayKumarr** [AISViz/aisdb-client#17]
Loading the provided **test_data_20210701.csv** available in aisdb > tests > testdata
It is also generating error.

**Comment by gabrielspadon** [comment]
Is this a duplicate issue? seems we have this mentioned in other opened issues.

**Comment by JayKumarr** [comment]
> Is this a duplicate issue? seems we have this mentioned in other opened issues.

yes it is mentioned, but it is solved in the newly merged branch.

**Comment by JayKumarr** [comment]
Decoding tested on Postgres
