### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by gabrielspadon** [AISViz/aisdb-client#35]
@JayKumarr and @Jinnkunn, whenever you can, could you please add two other algorithms for interpolation? One is the great-circle interpolation and the other is interpolation with polylines for better handling curves. Thanks!

**Comment by JayKumarr** [comment]
I have added the great-circle interpolation, however, I cannot find the **interpolation with polyline**
check these links out and let me know:
https://www.mathworks.com/help/map/geographic-interpolation-of-vectors.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.barycentric_interpolate.html#scipy.interpolate.barycentric_interpolate
