### ISSUE TITLE
Documentation Tutor Chatbot for AISdb

### ISSUE THREAD

**Issue by gabrielspadon** [AISViz/aisdb-client#7]
I suggest the development and integration of a chatbot that is trained with LangChain and an open-source Language Model (LLM). This chatbot will be created to act as a tutor for the AISdb documentation. Its purpose is to make it easier for new users to onboard and provide ongoing support to help them navigate the various functionalities of AISdb. The chatbot will be designed to provide code examples, assist in debugging, and offer guidance based on the user's needs. The effectiveness of this tool will depend on the quality and completeness of the existing documentation. However, given the wealth of open-source tools and pre-existing code available, the potential benefits of this initiative are substantial. To develop the chatbot, I suggest exploring models available on Hugging Face's Model Hub. These models have been trained on various data and could provide a solid foundation for our chatbot.

**Comment by Jinnkunn** [comment]
I will add the following topic to our documentation first:

1. Querying data with

- a specific area
- a specific time range
- vessel characters (e.g., speed...)

2. Export Data to

- CSV
- SQLite

**Comment by gabrielspadon** [comment]
We have developed a Gemini-based RAG solution that interacts with the LLM. However, this will be included as part of the tutorials, allowing anyone to deploy their own model and run it locally. As a result, I am closing this issue.
