### ISSUE TITLE
Open Source Data Importation

### ISSUE THREAD

**Issue by gabrielspadon** [AISViz/aisdb-client#9]
@JayKumarr, as we are downsizing AISdb to only work with the data and not to keep offering outsourced services, it would be great if we could show people how they can use AISdb with open-source data. The Spire data we have is not publicly sharable, but we do have data from here that can be freely used https://coast.noaa.gov/digitalcoast/contributing-partners/marinecadastregov.html. Could you work on a way to show people, either with a script or with Python code how can we ingest that data in AISdb databases for later use?

**Comment by JayKumarr** [comment]
**Next Task:** Importing the Data from NOAA and AISHub
